### ISSUE TITLE
[BUG] No id after rok update + truncate last digit of kp

### ISSUE THREAD

**Issue by oldguy60** [Cyrexxis/RokTracker#111] opened 2024-12-11 05:32 UTC
**Describe the bug**
When copying the information, the scanner will truncate the last digit of players that have KP that is 11 digits,   IE:  27,123,456,789 will be saved as  2,712,345,678 

I ran 3 scans and all 3 scans produced the same results, none of the players scanned had a modified background from SVIP 19.

Also When recording the player ID's  it will randomly use -3 for the payer ID and it will also truncate the ID, sometimes the start, sometimes the end, can be 1 digit or 3 that are missing
(This can not be duplicated for the same players to have errors on the ID numbers)

![2024-12-10 23 21 17](https://github.com/user-attachments/assets/f37bdad8-a88f-48a8-aa8f-54122dda2fcd)

**Your Setup (please complete the following information):**
 - OS:Windows 11
 - Bluestacks Version: 5.14.22.1003 N64
 - Android of Bluestacks: Nougat 64-bit
 - Tracker Version: v5.0.0

**Additional context**

**Comment by Cyrexxis** [comment] 2024-12-11 21:09
Overall this is a duplicate of #110 but the mention of a different background for svip is also important. I am very sure that a change in the background would also mess up the scan. Do people actually use it? If that is the case I need to find a person that uses the other background and start experimenting with settings.

**Comment by oldguy60** [comment] 2024-12-11 21:21
Prior to the update, last couple of weeks, we have multiple accounts with the flames type background.  Only on one account did I run into an issue on the recording of the KP, the account has 27 billion KP and the scanner would add a "1" between the 2 & 7 and be recorded as 217 billion. This was only an issue on the one account, those that were 1x billion were recorded properly.

**Comment by Cyrexxis** [comment] 2024-12-11 22:04
Ah that is good to hear, then probably no changes are needed. (The added 1 is probably a typical ocr issue again)

**Comment by oldguy60** [comment] 2024-12-12 02:09
Not sure if i just update this or make a new post, but the first bug issue from my original post is still there.
I am using v5.0.1 and the issue with KP for players over 10B is still there,  it truncates the last digit of any KP value with 11 characters.   So 12,345,678,901   is recorded as 1,234,567,890.

Also the log says "kills don't check out and need to be manually checked" for every account scanned.  I checked about 20 accounts and the recorded t4&t5 kills were correct and matched the KP recorded ( other then those with 11 digit kp values)
[kingdom-scanner.log](https://github.com/user-attachments/files/18104559/kingdom-scanner.log)

**Comment by Cyrexxis** [comment] 2024-12-12 11:10
Oh, my bad, I have missed that part of the issue. I need to move the scan area a bit more to the right in that case. I'll test that and then push another release.

**Comment by Cyrexxis** [comment] 2024-12-12 21:08
This should be fixed with version 5.0.2. I am closing this issue, but feel free to reopen it if there are still problems with it.

**Closed by Cyrexxis** 2024-12-12 21:08 UTC
Labels: bug
